# Colored makepkg-like functions
msg_blue() {
  printf "${BLUE}==>${BOLD} $1${ALL_OFF}\n"
}

warn1() {
  printf "${BLUE}==>${YELLOW} WARNING:${WHITE} $1${ALL_OFF}\n"
}

warn2() {
  printf "${BLUE}==>${WHITE} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="${ALL_OFF}$(tput bold)"
BLACK="${BOLD}$(tput setaf 0)"
RED="${BOLD}$(tput setaf 1)"
GREEN="${BOLD}$(tput setaf 2)"
YELLOW="${BOLD}$(tput setaf 3)"
BLUE="${BOLD}$(tput setaf 4)"
MAGENTA="${BOLD}$(tput setaf 5)"
CYAN="${BOLD}$(tput setaf 6)"
WHITE="${BOLD}$(tput setaf 7)"

pre_install() {
  warn1 'Consider switching to a different browser.'
  warn2
  warn2 'Midori has not been updated for CVE-2024-9680.  There have been'
  warn2 '"reports of this vulnerability being exploited in the wild."'
  warn2
  warn2 'For more information, visit:'
  warn2 '    https://www.mozilla.org/en-US/security/advisories/mfsa2024-51'
}

pre_upgrade() {
  pre_install
}
